name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        node-version: [20.10.0]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: '${{ matrix.node-version }}'

      - name: Build
        run: |
          npm install
          npm run test
          npm run build
