name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        node-version: [20.10.0]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: '${{ matrix.node-version }}'

      - name: Setup environment
        run: gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output calendar-service-account.json calendar-service-account.json.gpg
        env:
          PASSPHRASE: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_PASSPHRASE }}

      - name: Download basic.ics file
        run: curl -o dist/basic.ics https://calendar.google.com/calendar/ical/finos.org_fac8mo1rfc6ehscg0d80fi8jig%40group.calendar.google.com/public/basic.ics

      - name: Get events from Google API
        run: npm run get-events

      - name: Build
        run: |
          npm install
          npm run build
